image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      touch /tmp/.npm-lock
      npm install && npm run build && make && nvm install 12.13.0
      rm /tmp/.npm-lock
    name: init
  - command: sudo docker-up
    name: docker
  - init: |
      echo -n "Waiting for init script to complete before spinning things up. This can take a few minutes due to npm package installation. Check the init terminal window for progress..."
      sleep 1 && while [ -f /tmp/.npm-lock ]; do echo -n "..." && sleep 2; done
    command: echo && source ./gitpod.spin-up.sh
    name: terminal