image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npm run build && make && sudo docker-up && docker-compose -f docker-compose.dev.yml up -d && nvm install 12.13.0
    command: npm run start
